/********
    create column table with TEXT data type column with text analysis and text mining
    only sql console
********/

CREATE COLUMN TABLE blogs(
    ID BIGINT NOT NULL primary key GENERATED BY DEFAULT AS IDENTITY,
    BLOGCONTENT TEXT FAST PREPROCESS OFF SEARCH ONLY OFF ASYNC TEXT ANALYSIS ON TEXT MINING ON
);
